### ISSUE TITLE
Visual Studio 2015 Compile Error for MRI-Loader and MRI-Patch

### ISSUE THREAD

**Issue by Dedsec1** [IRDeNial/MRI-Loader#1]
Hi, 

iam getting the following Errors when trying to compile both MRI-Loader and MRI-Patch. also can you add support for the following Programs inside the MRI folder, FMOD.exe. ProcessAnalyzer.exe.  StartupManager.exe and SystemUpdater.exe.

MRI-Loader Error Log

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)		no suitable constructor exists to convert from "TCHAR [260]" to "std::basic_string<char, std::char_traits<char>, std::allocator<char>>"	MRI-Loader	c:\Users\Administrator\Downloads\MRI-Loader-master\MRI-Loader-master\MRI-Loader\MRI-Loader.cpp	21	

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)		no suitable constructor exists to convert from "TCHAR [260]" to "std::basic_string<char, std::char_traits<char>, std::allocator<char>>"	MRI-Loader	c:\Users\Administrator\Downloads\MRI-Loader-master\MRI-Loader-master\MRI-Loader\MRI-Loader.cpp	23	

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)		argument of type "TCHAR *" is incompatible with parameter of type "LPCSTR"	MRI-Loader	c:\Users\Administrator\Downloads\MRI-Loader-master\MRI-Loader-master\MRI-Loader\MRI-Loader.cpp	48	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2440	'initializing': cannot convert from 'TCHAR [260]' to 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>'	MRI-Loader	c:\users\administrator\downloads\mri-loader-master\mri-loader-master\mri-loader\mri-loader.cpp	21	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2440	'initializing': cannot convert from 'TCHAR [260]' to 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>'	MRI-Loader	c:\users\administrator\downloads\mri-loader-master\mri-loader-master\mri-loader\mri-loader.cpp	23	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2664	'BOOL DetourCreateProcessWithDllA(LPCSTR,LPSTR,LPSECURITY_ATTRIBUTES,LPSECURITY_ATTRIBUTES,BOOL,DWORD,LPVOID,LPCSTR,LPSTARTUPINFOA,LPPROCESS_INFORMATION,LPCSTR,PDETOUR_CREATE_PROCESS_ROUTINEA)': cannot convert argument 8 from 'TCHAR [260]' to 'LPCSTR'	MRI-Loader	c:\users\administrator\downloads\mri-loader-master\mri-loader-master\mri-loader\mri-loader.cpp	48	

MRI-Patch Log

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)		no suitable constructor exists to convert from "TCHAR [260]" to "std::basic_string<char, std::char_traits<char>, std::allocator<char>>"	MRI-Loader	c:\Users\Administrator\Downloads\MRI-Loader-master\MRI-Loader-master\MRI-Loader\MRI-Loader.cpp	21	

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)		no suitable constructor exists to convert from "TCHAR [260]" to "std::basic_string<char, std::char_traits<char>, std::allocator<char>>"	MRI-Loader	c:\Users\Administrator\Downloads\MRI-Loader-master\MRI-Loader-master\MRI-Loader\MRI-Loader.cpp	23	

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)		argument of type "TCHAR *" is incompatible with parameter of type "LPCSTR"	MRI-Loader	c:\Users\Administrator\Downloads\MRI-Loader-master\MRI-Loader-master\MRI-Loader\MRI-Loader.cpp	48	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2664	'int MessageBoxW(HWND,LPCWSTR,LPCWSTR,UINT)': cannot convert argument 2 from 'const char [62]' to 'LPCWSTR'	MRI-Patch	c:\users\administrator\downloads\mri-loader-master\mri-loader-master\geeksquadmri crack\geeksquadmri crack.cpp	49	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2664	'int MessageBoxW(HWND,LPCWSTR,LPCWSTR,UINT)': cannot convert argument 2 from 'const char [62]' to 'LPCWSTR'	MRI-Patch	c:\users\administrator\downloads\mri-loader-master\mri-loader-master\geeksquadmri crack\geeksquadmri crack.cpp	57	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2664	'int MessageBoxW(HWND,LPCWSTR,LPCWSTR,UINT)': cannot convert argument 2 from 'const char [34]' to 'LPCWSTR'	MRI-Patch	c:\users\administrator\downloads\mri-loader-master\mri-loader-master\geeksquadmri crack\geeksquadmri crack.cpp	64	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2664	'int MessageBoxW(HWND,LPCWSTR,LPCWSTR,UINT)': cannot convert argument 2 from 'const char [13]' to 'LPCWSTR'	MRI-Patch	c:\users\administrator\downloads\mri-loader-master\mri-loader-master\geeksquadmri crack\geeksquadmri crack.cpp	70	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2664	'int MessageBoxW(HWND,LPCWSTR,LPCWSTR,UINT)': cannot convert argument 2 from 'char [150]' to 'LPCWSTR'	MRI-Patch	c:\users\administrator\downloads\mri-loader-master\mri-loader-master\geeksquadmri crack\geeksquadmri crack.cpp	85	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2664	'int MessageBoxW(HWND,LPCWSTR,LPCWSTR,UINT)': cannot convert argument 2 from 'char [150]' to 'LPCWSTR'	MRI-Patch	c:\users\administrator\downloads\mri-loader-master\mri-loader-master\geeksquadmri crack\geeksquadmri crack.cpp	87	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2664	'int MessageBoxW(HWND,LPCWSTR,LPCWSTR,UINT)': cannot convert argument 2 from 'char [500]' to 'LPCWSTR'	MRI-Patch	c:\users\administrator\downloads\mri-loader-master\mri-loader-master\geeksquadmri crack\geeksquadmri crack.cpp	100	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2664	'int MessageBoxW(HWND,LPCWSTR,LPCWSTR,UINT)': cannot convert argument 2 from 'char [150]' to 'LPCWSTR'	MRI-Patch	c:\users\administrator\downloads\mri-loader-master\mri-loader-master\geeksquadmri crack\geeksquadmri crack.cpp	109	

Thanks 

Dedsec1

**Comment by IRDeNial** [comment]
Solved.  VS was compiling under x64.

As a note for anyone viewing this:
Since this is using MS Detours 3.0 Express, this will only compile under x86.  Compiling under x64 will produce the errors shown in this issue.
